name: Put SSM version for deploy
description: This action updates the SSM parameter with the new image version for deployment.

inputs:
  version:
    required: true
    description: "Version of the image to be deployed. If not provided, it will be set to 'latest'."
  environment:
    required: true
    description: "Environment for which the SSM parameter is being updated."
  ecr-repository:
    required: true
    description: "ECR repository name."
  aws-access-key-id:
    required: true
    description: "AWS access key ID for authentication."
  aws-secret-access-key:
    required: true
    description: "AWS secret access key for authentication."
  aws-region:
    required: true
    description: "AWS region where the ECR repository is located."
    default: "us-east-1"
  secrets-environment:
    required: false
    description: "Environment for which the secrets are being used."

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: "true"
        registry-type: public

    - name: Change ${{ inputs.ecr-repository }} version to ${{ env.version }} on ${{ inputs.environment }} in SSM parameter store
      shell: bash
      env:
        ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        IMAGE_VERSION: ${{ inputs.version }}
        ENVIRONMENT: ${{ inputs.environment }}
        SSM_PARAMETER_NAME: /${{ inputs.environment }}/${{ inputs.ecr-repository }}/version'
        SECRETS_ENVIRONMENT: ${{ inputs.secrets-environment }}
      run: node ./scripts/check-and-change-image.js
